#!/usr/bin/env bash
PACKERDIR=~/.local/share/nvim/site/pack/packer/start/packer.nvim
WORKDIR=$(pwd)
rm -r ~/.config/nvim
mkdir -p ~/.config/nvim
mkdir -p ~/.config/nvim/lua

# link wholesale
for f in `gfind . -regex ".*\.vim$\|.*\.lua$"`; do
    echo $f
    ln -s $WORKDIR/$f ~/.config/nvim/$f
done

if [ ! -d $PACKERDIR ]
then
	git clone https://github.com/wbthomason/packer.nvim\
	 $PACKERDIR
fi

