#!/usr/bin/env bash
set -x

PACKERDIR=~/.local/share/nvim/site/pack/packer/start/packer.nvim
WORKDIR=$(pwd)

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    FIND="find"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    FIND="gfind"
else
    echo "unknown OS"
    exit 1
fi

rm -r ~/.config/nvim
mkdir -p ~/.config/nvim
mkdir -p ~/.config/nvim/lua

# link wholesale
for f in `$FIND . -regex ".*\.vim$\|.*\.lua$"`; do
    echo $f
    ln -s $WORKDIR/$f ~/.config/nvim/$f
done

if [ ! -d $PACKERDIR ]
then
	git clone https://github.com/wbthomason/packer.nvim\
	 $PACKERDIR
fi

